config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'comments/new'
  get 'comments/edit'
  get 'comments/create'
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  get 'users/new'
  root 'static_pages#home'
  get 'static_pages/home'
  get '/help', to: 'static_pages#help', as: 'helf'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users do
    member do
      get :following, :followers
    end
  end
    mount ActionCable.server => '/cable'

  devise_for :users,
             controllers: {
               #  :omniauth_callbacks => "users/omniauth_callbacks",
               omniauth_callbacks: 'users/omniauth_callbacks',
               sessions: 'users/sessions',
               registrations: 'users/registrations'
             }

  resources :account_activations, only: [:edit]
  resources :password_resets, only: %i[new create edit update]
  resources :microposts, only: %i[create destroy] do
    resource :emote do
      get :count_emoji
    end
  end
  resources :comments

  resources :relationships, only: %i[create destroy]
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  has_many :emotes, dependent: :destroy
  has_one_attached :image
  has_many :comments, dependent: :destroy
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: 'must be a valid image format' },
  size: { less_than: 5.megabytes, message: 'should be less than 5MB' }
  def self.schedule_micropost
    @micropost_count = Micropost.where("DATE(created_at) = ?", Date.today-1).count
    client = Slack::Web::Client.new
    client.auth_test
    client.chat_postMessage(channel: '#test_rails', text: "có #{@micropost_count} bài đăng mới")
  end
  # Returns a resized image for display. TRA VE hinh anh da sua doi
  after_destroy_commit do
    broadcast_remove_to self
  end
  after_update_commit do
    broadcast_replace_to self
  end
  def emotes_size(key)
    self.emotes.select { |e| e.emoji == key }.size
  end
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

# Service to download ftp files from the server
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i[create destroy]
  before_action :correct_user, only: :destroy
  def create
    @micropost = current_user.microposts.build(micropost_params)
    @micropost.image.attach(params[:micropost][:image])
    if @micropost.save
      flash[:success] = 'Micropost created!'
      redirect_to root_url
    else
      @feed_items = current_user.feed.paginate(page: params[:page])
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = 'Micropost deleted'
    if request.referrer.nil? || request.referrer == microposts_url
      redirect_to root_url
    else
      redirect_to request.referrer
    end
  end

  private

  def micropost_params
    params.require(:micropost).permit(:content, :image)
  end

  def correct_user
    @micropost = current_user.microposts.find_by(id: params[:id])
    redirect_to root_url if @micropost.nil?
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

# Service to download ftp files from the server
module MicropostsHelper
end

app/views/microposts/_like_link.html.erb
<%= link_to like_micropost_path(micropost), method: :patch, remote: true, id: "like-link-#{micropost.id}" do %>
<% if current_user.voted_up_on?(micropost) %>
  UNLIKE
  <b>
    <%= micropost.cached_votes_score %>
  </b>

<% elsif current_user.voted_down_on?(micropost) %>
  LIKE
  <b>
    <%= micropost.cached_votes_up %>
  </b>

<% else %>
  LIKE
  <b>
    <%= micropost.cached_votes_score %>
  </b>

<% end %>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.image if micropost.image.attached? %>
  </span>
  <span id="emoji" class="timestamp">
    <!-- emotes -->

    <% Emoji.all.each do |emoji| %>
      <% size = micropost.emotes_size(emoji[:key]) %>
      <%= link_to count_emoji_micropost_emote_path(micropost, emote: emoji[:key]), class: "emoji-link" do %>
        <%= image_tag File.join('emojis', emoji[:key]), size: '25x25', title: emoji[:text] %>
        <%= content_tag :span, size, class: 'count' %>
      <% end %>
    <% end %>

    <!-- end  -->
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
    <% if current_user?(micropost.user) %>
      <%= button_to "delete", micropost, method: :delete,
      data: { confirm: "You sure?" } %>
    <% end %>
  </span>
          <!--  -->


  notification <%= @unread.count %>
  <br>
  <%= @read.each do |notification| %>
     <%= notification.to_notification.message %>

  <% end %>>
  <hr>
  <br>
  <h5>Comment :</h5>
  <%= @comment = micropost.comments %>
  <div id="comments">
    <span id="comment-<%= micropost.id %>">
      <%= render @comment %>
    </span>
  </div>
  <span id="form">
    <%= form_for Comment.new ,remote: true do |f| %>
      <%= render 'shared/error_messages', object: f.object %>
      <div class="field">
        <%= f.hidden_field :micropost_id, value: micropost.id %>
        <%= f.hidden_field :user_id, value: current_user.id %>
        <%= f.text_area :body, placeholder: "Viết bình luận ...", class: "form-control" %>
      </div>
      <%= f.submit "Comment", class: "btn btn-primary" %>
    <% end %>
  </span>
</li>

app/views/microposts/like.js.erb
document.getElementById("like-link-<%= @micropost.id %>").innerHTML = "<%= j render "microposts/like_link", micropost: @micropost %>";